@CMS_CSharp_HostAddress = http://localhost:5089

GET {{CMS_CSharp_HostAddress}}/
Accept: application/json

###

GET {{CMS_CSharp_HostAddress}}/health
Accept: text/plain

###

GET {{CMS_CSharp_HostAddress}}/database/status
Accept: application/json

###

GET {{CMS_CSharp_HostAddress}}/api/devices/search?market_name=Reno
Accept: application/json

###
